// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvgquiqywgwdgndoeapv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2Z3F1aXF5d2d3ZGduZG9lYXB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMzQ4NDUsImV4cCI6MjA3MzYxMDg0NX0.sh3Ne0s20lVHJ3oNmT3EImdTsXTf7YML0UOxByo7PmE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});